overwrite: true

require:
  - ts-node/register

schema:
  - "./schema.graphql"

hooks:
  afterAllFileWrite:
    - prettier --write

extensions:
  codegen:
    generates:
      types.ts:
        plugins:
          - typescript
          - typescript-resolvers
        config:
          contextType: mercurius#MercuriusContext
          useIndexSignature: true
